baseURL = 'https://0xmoonrise.github.io/'
languageCode = 'en-us'
title = 'Captain Jack Moonrise'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20


[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[taxonomies]
  category = 'categories'
  tag = 'tags'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNumbersInTable = false
    noClasses = false
    noHl = true
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true
